"""
Loader for PFSAHA NNN level/partition-function tables extracted from atlas7v.for.

The data file `pfsaha_levels.npz` is generated by
`synthe_py/tools/extract_pfsaha_levels.py` and contains the Fortran NNN(6,374)
array exactly as declared in PFSAHA.
"""

from __future__ import annotations

from pathlib import Path
from typing import Dict

import numpy as np


_DATA_PATH = Path(__file__).resolve().parents[1] / "data" / "pfsaha_levels.npz"


def _load_nnn() -> np.ndarray:
    if not _DATA_PATH.exists():
        raise FileNotFoundError(
            f"PFSAHA NNN levels file not found: {_DATA_PATH}.\n"
            "Run synthe_py/tools/extract_pfsaha_levels.py to generate it "
            "from src/atlas7v.for."
        )
    data = np.load(_DATA_PATH, allow_pickle=False)
    if "NNN" not in data.files:
        raise KeyError(f"'NNN' array not found in {_DATA_PATH}")
    nnn = np.asarray(data["NNN"], dtype=np.int64)
    if nnn.shape != (6, 374):
        raise ValueError(f"Unexpected NNN shape {nnn.shape}, expected (6, 374)")
    return nnn


NNN: np.ndarray = _load_nnn()


